global:
  scrape_interval: 5s

# scrape_configs:
#   - job_name: 'local-cinema'
#     metrics_path: '/metrics'
#     static_configs:
#       - targets: ['host.docker.internal:5000']

scrape_configs:
  - job_name: 'render-cinema'
    metrics_path: '/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['assignment12-ia30.onrender.com']